### PR TITLE
Add dependabot and bump maven dependencies versions

### PR DESCRIPTION
**Pull request by spencercjh**
I add dependabot to upgrade the maven dependencies.

### CODE REVIEW

**Comment by spencercjh** [comment]
@lanwen

**Comment by spencercjh** [comment]
I have just recently started using this project and participating in this community. I would like to ask if you have any plans to release a version?

**Comment by lanwen** [comment]
@spencercjh hey, thanks for the contribution, however, this housekeeping doesn't really involve anything user-visible, please correct me if I'm wrong. So I don't have plans to release it without other stuff. I would appreciate the help of transferring out of the travis to github actions though to make the release process easier.

**Comment by spencercjh** [comment]
> @spencercjh hey, thanks for the contribution, however, this housekeeping doesn't really involve anything user-visible, please correct me if I'm wrong. So I don't have plans to release it without other stuff.

You are right. 

> I would appreciate the help of transferring out of the travis to github actions though to make the release process easier.

I can help you. Wait for my PR. 😄

**Pull request merged**
